### ISSUE TITLE
Develop UI to visualise the info for reservation

### ISSUE THREAD

**Issue by chisty38** [chisty38/ComP_313_proJ_02_restuarant#10]
all food orders, the number of people that have booked, customer information for all reservations and customer information

**Comment by haocencol** [comment]
Please attach a file with the UI design proposal for this issue.

**Comment by chisty38** [comment]
Complete UI design is still in progress....

**Comment by haocencol** [comment]
Please upload a design by the end of today.  An UI design should not take 6 days.

**Comment by chisty38** [comment]
https://github.com/chisty38/androidApp_Firbase_Project_02....we uploaded all r code for the mobile app..

**Comment by Soo7379** [comment]
![image](https://user-images.githubusercontent.com/23502836/52819099-7cd32f80-3076-11e9-8b3f-2d3113dd238c.png)

![login_page](https://user-images.githubusercontent.com/23502836/52819213-c459bb80-3076-11e9-956d-979534770080.PNG)

![signup_page](https://user-images.githubusercontent.com/23502836/52819222-c885d900-3076-11e9-8666-e3cc0d98f106.PNG)

![reservation_page](https://user-images.githubusercontent.com/23502836/52819229-cc196000-3076-11e9-960f-7c77fc48840b.PNG)

**Comment by Soo7379** [comment]
These UI designs are basic that shows what functionalities we are having for our project. They will be improved for sure in the future.
