### ISSUE TITLE
view restaurant’s food menu

### ISSUE THREAD

**Issue by chisty38** [chisty38/ComP_313_proJ_02_restuarant#6]

**Comment by Haydar77** [comment]
Food menu done, available dates will be done approx. Friday

**Comment by haocencol** [comment]
#12

**Comment by Haydar77** [comment]
![dates](https://user-images.githubusercontent.com/23483593/53147757-8bd64800-3576-11e9-8d48-b8d65cb1ed88.png)
![menu](https://user-images.githubusercontent.com/23483593/53147758-8bd64800-3576-11e9-9b2b-2c2d550a6a01.png)
![menu1](https://user-images.githubusercontent.com/23483593/53147759-8bd64800-3576-11e9-8975-ce0d1e038d53.png)
![menu2](https://user-images.githubusercontent.com/23483593/53147760-8bd64800-3576-11e9-9475-93e7db9c29fd.png)

Done

**Comment by Sahil754** [comment]
Reaching point in project where iteration 6 is being done.
